drop table IF EXISTS RECIBOS;
drop table IF EXISTS DOACAO;
drop table IF EXISTS CONTRIBUINTE;
drop table IF EXISTS FUNCIONARIO;
drop table IF EXISTS CAMPANHA;
drop table IF EXISTS CARGO;
drop table IF EXISTS TABULACAO;
drop table IF EXISTS ENDERECO;
drop table IF EXISTS FORMA_PAGAMENTO;
drop table IF EXISTS USUARIO;

CREATE TABLE CAMPANHA (
	ID SERIAL PRIMARY KEY,
	DESCRICAO TEXT NOT NULL,
	DATA_INICIO DATE NOT NULL,
	DATA_FIM DATE NULL	
);

comment on table CAMPANHA is 'TABELA PARA CONTROLAR QUAL CAMPANHA O DOADOR PERTENCE';
comment on column CAMPANHA.DESCRICAO is 'CAMPANHA UNITRI';
comment on column CAMPANHA.DATA_INICIO is 'INICIO CAMPANHA';
comment on column CAMPANHA.DATA_FIM is 'FIM CAMPANHA';

CREATE TABLE CARGO (
	ID SERIAL PRIMARY KEY,
	DESCRICAO TEXT NOT NULL	
);

comment on table CARGO is 'CONTROLE DE CARGOS';

CREATE TABLE ENDERECO (
	CEP integer PRIMARY KEY,
	LOGRADOURO TEXT NOT NULL,
	BAIRRO TEXT NOT NULL,
	CIDADE TEXT NOT NULL,
	UF TEXT NOT NULL
);

CREATE TABLE FORMA_PAGAMENTO (
	ID SERIAL PRIMARY KEY,
	DESCRICAO TEXT NOT NULL	
);

comment on table FORMA_PAGAMENTO is 'TABELA PARA CONTROLE DE FORMA DE PAGAMENTO POR CONTRIBUINTE, MENSAGEIRO, CARTAO , DDA';
comment on column FORMA_PAGAMENTO.DESCRICAO is 'MENSAGEIRO, CARTAO , DDA';

CREATE TABLE USUARIO (
	ID SERIAL PRIMARY KEY,
	NOME TEXT NOT NULL,
	USUARIO TEXT NOT NULL,
	SENHA TEXT NULL	
);

CREATE TABLE FUNCIONARIO (
	ID SERIAL PRIMARY KEY,
	ID_USUARIO INTEGER REFERENCES USUARIO (ID) NOT NULL,
	ID_CARGO INTEGER REFERENCES CARGO (ID) NOT NULL,
	CEP INTEGER REFERENCES ENDERECO (CEP) NOT NULL,
	NOME TEXT NOT NULL,
	SOBRENOME TEXT DEFAULT NULL,
	SEXO CHAR DEFAULT NULL,
	CPF TEXT DEFAULT NULL,
	EMAIL TEXT DEFAULT NULL,
	TELEFONE_1 TEXT DEFAULT NULL,
	TELEFONE_2 TEXT DEFAULT NULL,
	NUMERO_RESIDENCIA INTEGER DEFAULT NULL,
	COMPLEMENTO_RESIDENCIA TEXT DEFAULT NULL,
	SITUACAO CHAR	
);

comment on column FUNCIONARIO.SEXO is 'M = Masculino, F = Feminino';
comment on column FUNCIONARIO.SITUACAO is 'A = ATIVO, I = INATIVO';

CREATE TABLE CONTRIBUINTE (
	ID SERIAL PRIMARY KEY,
	ID_FORMA_PAGAMENTO INTEGER REFERENCES FORMA_PAGAMENTO (ID) NOT NULL,
	ID_FUNCIONARIO INTEGER REFERENCES FUNCIONARIO (ID) NOT NULL,
	NOME TEXT NOT NULL,
	SOBRENOME TEXT DEFAULT NULL,
	TIPO CHAR DEFAULT NULL,
	SEXO CHAR DEFAULT NULL,
	DATA_NASCIMENTO DATE DEFAULT NULL,
	EMAIL TEXT DEFAULT NULL,
	TELEFONE_1 TEXT DEFAULT NULL,
	TELEFONE_2 TEXT DEFAULT NULL,
	NUMERO_RESIDENCIA INTEGER DEFAULT NULL,
	COMPLEMENTO_RESIDENCIA TEXT DEFAULT NULL,
	DATA_CADASTRO DATE DEFAULT NULL,
	CEP INTEGER REFERENCES ENDERECO (CEP) NOT NULL,
	SITUACAO CHAR (1) DEFAULT NULL
);

comment on table CONTRIBUINTE is 'TABELA ONDE ENCONTRA-SE TODOS CONTRIBUINTES CADASTRADOS, TABELA PARA CADASTRAR NOVOS CONTRIBUINTES';
comment on column CONTRIBUINTE.TIPO is 'J = JURIDICA, F = FISICA';
comment on column CONTRIBUINTE.SEXO is 'M = Masculino,  F = Feminino';
comment on column CONTRIBUINTE.DATA_CADASTRO is 'DATA SALVA PELA ACAO DO SISTEMA CURRENT DATE';
comment on column CONTRIBUINTE.SITUACAO is 'A = ATIVO, I = INATIVO';

CREATE TABLE DOACAO (
	NUMERO_RECIBO INTEGER PRIMARY KEY,
	VALOR NUMERIC NOT NULL,
	STATUS CHAR DEFAULT NULL,
	DATA_OPERACAO DATE DEFAULT NULL,
	DATA_VENCIMENTO DATE DEFAULT NULL,
	DATA_BAIXA DATE DEFAULT NULL,
	PARCELA TEXT DEFAULT NULL,
	ID_CONTRIBUINTE INTEGER REFERENCES CONTRIBUINTE (ID) NOT NULL,
	ID_CAMPANHA INTEGER REFERENCES CAMPANHA (ID) NOT NULL,	
	ID_FORMA_PAGAMENTO INTEGER REFERENCES FORMA_PAGAMENTO (ID) NOT NULL,
	ID_FUNCIONARIO_ATENDENTE INTEGER REFERENCES FUNCIONARIO (ID) NOT NULL,
	ID_FUNCIONARIO_MOTOBOY INTEGER REFERENCES FUNCIONARIO (ID) NOT NULL
);

comment on table DOACAO is 'TABELA ONDE ENCONTRA-SE TODOS DOACAO PRODUZIDOS';
comment on column DOACAO.VALOR is 'VALOR DOACAO';
comment on column DOACAO.STATUS is 'B = BAIXADO, G = GERADO, R = REAGENDADO, C = CANCELADO';
comment on column DOACAO.DATA_OPERACAO is 'DATA PRODUCAO RECIBO';
comment on column DOACAO.DATA_VENCIMENTO is 'DATA VENCIMENTO RECIBO';
comment on column DOACAO.DATA_BAIXA is 'QUANDO OUVE BAIXA, CANCELAMENTO OU REAGENDAMENTO';
comment on column DOACAO.PARCELA is 'QUANTIDADE PARCELAS PRODUZAIDAS 1/N';

CREATE TABLE EMPRESA (
	ID SERIAL PRIMARY KEY,
	NOME_FANTASIA TEXT NOT NULL,
	RAZAO_SOCIAL TEXT DEFAULT NULL,
	CNPJ TEXT DEFAULT NULL,
	EMAIL TEXT DEFAULT NULL,
	TELEFONE_1 TEXT DEFAULT NULL,
	TELEFONE_2 TEXT DEFAULT NULL,
	CEP INTEGER REFERENCES ENDERECO (CEP) NOT NULL,
	NUMERO_RESIDENCIA INTEGER DEFAULT NULL,
	COMPLEMENTO_RESIDENCIA TEXT DEFAULT NULL,
	SITUACAO CHAR
);